# Generated by Django 4.2.6 on 2023-10-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
